############################
## ---------------------- ##
## | Plugin by MPlugins | ##
## ---------------------- ##
############################

####################
## MySQL Settings ##
####################

mysql:
  username: 'root'
  password: ''
  database: 'mplugins'
  host: 'localhost'